name = "wishbone_test"
description = "Ada Program for WishboneTest on NEORV32"
version = "0.1.0-dev"

authors = ["Dipen R"]
maintainers = ["Dipen R <dipenarathod@gmail.com>"]
maintainers-logins = ["dipenarathod"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
neorv32_hal = "*"
bare_runtime= "*"
[[pins]]
neorv32_hal = { path = ".." } 
